parameters:
    genj_faq.admin.question_admin.class: Genj\FaqBundle\Admin\QuestionAdmin
    genj_faq.admin.question_admin.dashboard_group: 'dashboard.faq'

services:
    sonata.admin.genj_faq_question:
        class: %genj_faq.admin.question_admin.class%
        tags:
            - { name: sonata.admin, manager_type: orm, group: %genj_faq.admin.question_admin.dashboard_group%, label: "FAQ" }
        arguments:
            - ~
            - %genj_faq.entity.question.class%
            - ~
